runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)/$
    static_files: \1/index.html
    upload: .*/index.html

  - url: /(.*\.*)$
    static_files: \1
    upload: .*\.*$

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest

skip_files:
  # Default patterns skipped by App Engine, which must be repeated since
  # specifying skip_files overrides them otherwise.  See
  # https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  # Build files that have no effect in App Engine's runtime.
  - ^.*\.MF$
  - ^.*\.CMF$
  - ^.*\.so$
  - ^.*pywrap.+\.py$
  - ^.*\.jslib$
